### ISSUE TITLE
code sai

### ISSUE THREAD

**Issue by thuan05021996** [dajja/nestjs#4]
aymete judasau

**Comment by dajja** [comment]
ok

**Comment by thuan05021996** [comment]
`import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { UserModule } from './user/user.module';

@Module({
  imports: [UserModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
`### code lỏ

**Comment by dajja** [comment]
`import { Controller } from '@nestjs/common';
import { UserService } from './user.service';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) {}
}
`
fix the n

**Comment by dajja** [comment]
``

**Comment by dajja** [comment]
```javascript
import { Controller } from '@nestjs/common';
import { UserService } from './user.service';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) {}
}```

**Comment by dajja** [comment]
```javascript
console.log("hellowrold")
```

**Comment by dajja** [comment]
``import { Controller } from '@nestjs/common';
import { UserService } from './user.service';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) {}
}``

**Comment by dajja** [comment]
```import { Controller } from '@nestjs/common';
import { UserService } from './user.service';

@Controller('user')
export class UserController {
  constructor(private readonly userService: UserService) {}
}```
